### ISSUE TITLE
Sound Patcher broke in patchers merge

### ISSUE THREAD

**Issue by Utumno** [Sharlikran/wrye-bash#20]
As detailed the fixup commit here: https://github.com/wrye-bash/wrye-bash/commit/70306e70469fec30d0649b88965871710d4e9c7e

your commit here:

https://github.com/wrye-bash/wrye-bash/commit/ed5c017de7006de5a806cf9ef5f84982fc7ea1c4

broke the patcher as the SOUN record did not have any minDist1 attribute. I fixed that in this commit but I have two questions:

1. In https://github.com/wrye-bash/wrye-bash/commit/ed5c017de7006de5a806cf9ef5f84982fc7ea1c4 I see you replace the loops with `for recType, attrs in game.soundsTypes.iteritems():`. `game.soundsTypes` for oblivion is

    ```
soundsTypes = {
    "ACTI": ('sound',),
    "CONT": ('soundOpen','soundClose',),
    "CREA": ('footWeight','inheritsSoundsFrom','sounds',),
    "DOOR": ('soundOpen','soundClose','soundLoop',),
    "LIGH": ('sound',),
    "MGEF": ('castingSound','boltSound','hitSound','areaSound',),
#    "REGN": ('entries.sounds',),
    "SOUN": ('soundFile', 'minDist2', 'maxDist2', 'freqAdj2', 'staticAtten',
             'stopTime', 'startTime',),
    "WATR": ('sound',),
    "WTHR": ('sounds',),
}
   ```
   so as seen it contains more records than before - namely SOUN CREA and WATR. Is this intentional ?

2. game.soundsLongsTypes for oblivion is:
   ```
soundsLongsTypes = {'MGEF', 'ACTI', 'LIGH', 'WTHR', 'CONT', 'DOOR',
                    'SOUN', 'WEAP'} # those 2 were not included before
```
   so it does not include WATR and CREA from the new records while it does include WEAP. Again is this intentional ?

The arrays were introduced in your commit here: https://github.com/wrye-bash/wrye-bash/commit/4977f324773b892392f8665fbf992e37d0c29b54

Thanks

**Comment by Sharlikran** [comment]
Although commenting on Sharlikran 20 shouldn't take that long, I have some real life issues mainly 25 days to find a home as were were given a 90 day notice in July.  I am unable to comment until I move in regards to that.  Most changes are intentional as the records are all different including attributes added to accommodate the xEdit definitions for unknown or unused bytes of data that must be present to prevent truncating the record.

**Comment by Utumno** [comment]
Ok good luck with the house and all - once you find some time please have a look - brief:

1. is SOUN CREA and WATR records addition to the patcher working ?
2. Why WEAP is added to the soundsLongsTypes ? Why WATR and CREA are not ? We need a mod with those records and the sound tag to test if it blows

@Arthmoor - if you can test this - tag a mod with Sound that has also CRE and WATR records and see if patch is build correctly

**Comment by Sharlikran** [comment]
For any record not present in soundsLongsTypes that happened for one of two reasons. 1) I forgot 2) it tripped up the long fid conversion error.  I most defiantly will not be able to comment on errors in regards to the conversion of long fids.  The error has been present for quite some time and tiria (?SP can't remember the spelling at the moment) was not able to resolve it.  

You could have inadvertently resolved it with refactoring or other changes to GPath (or get path or whatever it's called) but I would have no idea.  Skyrim mods will suffice for testing but I wouldn't know which mods I was using when the error occurred.  I have posted about it in the forums but I don't have time to find any posts about it.  I also probably won't be able to find any GitHub comments from tiria (again ?SP) if I did any rebasing.

Sorry I can't be of more help at the moment.

**Comment by Utumno** [comment]
Alright went ahead and merged my fix but remains to be seen if mods with CREA and WATR records break the sound patcher (oblivion only I remind you). trira may be able to comment on the fid stuff - see commit above

**Comment by Sharlikran** [comment]
I kept what I wants from commit https://github.com/wrye-bash/wrye-bash/commit/70306e70469fec30d0649b88965871710d4e9c7e.  Thanks.

**Comment by Utumno** [comment]
Thac commit is deprecated - there are two commits on the dev branch however
