### ISSUE TITLE
Supress LOOT API Warning for SSE

### ISSUE THREAD

**Issue by Sharlikran** [Sharlikran/wrye-bash#21]
SSE Mode needs to suppress the LOOT API until game release and until @WrinklyNinja has time to update the API.  From what I understand it might not be updated for LOOT for several weeks.  It's not really a priority at the moment anyway.

@Utumno I did look at https://github.com/wrye-bash/wrye-bash/commit/721ade9edfe5abb4abce8ab158ca8467e8e63127 but I have made additional changes.  The branch I am working with is https://github.com/Sharlikran/wrye-bash/tree/330-skyrimse-support.

Please ignore the file changes I have made for now in regards to the Clean Data routines.  I will make additional updates and squash the commits once I have time.

**Comment by Utumno** [comment]
> AttributeError: type object 'loot_api.GameType' has no attribute 'sse'

This is thrown from the C++ and has nothing to do with Bash - it simply means there is no sse game type as far as loot is concerned.

You must load loot for skyrim

**Comment by Utumno** [comment]
SO probably `bush.game.fsName` should be skyrim in this case

**Comment by WrinklyNinja** [comment]
I'll probably go for `loot_api.GameType.tes5se` instead of `loot_api.GameType.sse` and the wait time will probably be < 1 week, not several.

To get it to stop failing as a temporary measure, just add an if statement before the `gameType = self.getLootApiGameType(bush.game.fsName)` line in `mods_metadata.py`, and check that `fsName` is not `SkyrimSE`.

Alternatively, try updating `getLootApiGameType()` to map `SkyrimSE` to `loot_api.GameType.tes5` and see if the API will still work.

**Comment by Utumno** [comment]
Although I find sse a nice addition I don't have time to look at it now.

**Comment by Sharlikran** [comment]
>> and the wait time will probably be < 1 week, not several.

I was just trying to be respectful that you may be busy.

>> Although I find sse a nice addition I don't have time to look at it now.

That's okay I'm going to try Wrinkly's suggestions and see if I can get it to work.  Otherwise I would just have to be patient and wait a bit.  Which is fine.  Thanks Utumno.

**Comment by Sharlikran** [comment]
@WrinklyNinja 

I tried adding  if not fsName == 'SkyrimSE': before the try and fsName is not defined as a global there so I can't make a check at that point.  So I went with leaving that alone and mapped tes5 to SkyrimSE.  Doing that gives me an error about Incompatible function arguments
```
The following argument types are supported:
    1. (loot_api.GameType, loot_api.GameType) -> bool
    Invoked with: GameType.tes5, SkyrimSE
```
Changing fsName = u'Skyrim' instead of SkyrimSE within __init__.py in the skyrim folder worked but it can't stay that way since it's going to share Skyrim and SkyrimSE .dat files and it wants to read the Skyrim load order folder in documents so it will break that load order.

I'll just be patient and wait for a proper update to the API when you have time.  I appreciate the suggestions so far.

**Comment by Sharlikran** [comment]
Actually the load order files being shared is due to other code I have to change.  I have to find that now.

**Comment by Sharlikran** [comment]
@Utumno

So I understand that you won't have time right now to look at support for this.  Also I'm going to be patient about the LOOT API.  However will Wrye be able to use different paths to plugins.txt?
```
def initialize_load_order_handle(mod_infos):
    global game_handle
    game_handle = games.game_factory(bush.game.fsName, mod_infos,
                                     _plugins_txt_path, _loadorder_txt_path)
```

For SSE displayName = u'Skyrim Special Edition' and fsName = u'SkyrimSE'.  For Skyrim displayName = u'Skyrim' and fsName = u'Skyrim'.  Wrye needs to look at (C:\Users\{{user name}}\AppData\Local\Skyrim Special Edition) for SSE and (C:\Users\{{user name}}\AppData\Local\Skyrim) for Skyrim.  Without parenthesis of course.

**Comment by Utumno** [comment]
Well the line that initializes the 'userApp dir is `dirs['userApp'] = localAppData.join(bush.game.fsName)` - so fsName should be `Skyrim Special Edition`. Search for other uses of fsName though to see if thios breaks other stuff

**Comment by Sharlikran** [comment]
Well I may want fsName to be SkyrimSE but in the intrest of doing it correctly and not how I want it, that's what it has to be then.  It's working now minus the LOOT API changes.

**Comment by Sharlikran** [comment]
Well it's going to complain about the strings files until libbsa is updated or until jowond7 updates BEA or some other BSA utility he is working on.

**Comment by Sharlikran** [comment]
Closing since Wrye Starts with the current API for Fallout 4 and Skyrim.
