### ISSUE TITLE
Add Basic SSE Support

### ISSUE THREAD

**Issue by Sharlikran** [Sharlikran/wrye-bash#22]
I don't feel like typing too much at the moment.

**Comment by Sharlikran** [comment]
@Arthmoor once there is time to supress the LOOT API warning hopefully Wrye Bash will finally start.  Upon trying to use a pre existing BSA file it caused SSE to freeze.  BSA_Opt will not read the new format.  So at this point I'm not in favor of allowing any legacy support for older Skyrim files.  Therefore, I feel the only allowed plugin version should be 1.70.

**Comment by Arthmoor** [comment]
The plugin format and version number has not changed. Only the BSAs need to be repacked for SSE. I've already tested that and confirmed it to be true.

There is one new record type that showed up for SSE and some additional data in weather files but that's it.

**Comment by Sharlikran** [comment]
Well then I'm a noob, I must have missed something for the version format.  I'll go look at it again.  Thanks for correcting me.

**Comment by Sharlikran** [comment]
For xEdit I'm waiting for the guys to decide on a few things and some internal game mode syntax.

**Comment by Hugues92** [comment]
Those are still BA , not BA2 ?

**Comment by Sharlikran** [comment]
Still BSA for SSE.

**Comment by Sharlikran** [comment]
@utumno I still need to rebase some things but my initial attempt at enabling a patcher gave me this error.
```
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 434, in main
    app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 3985, in Init
    self.InitData(progress)
  File "bash\basher\__init__.py", line 4032, in InitData
    bosh.modInfos.generateNextBashedPatch()
TypeError: generateNextBashedPatch() takes exactly 2 arguments (1 given)
```

**Comment by Utumno** [comment]
Yep a regression - the fix is already on dev :)

https://github.com/wrye-bash/wrye-bash/commit/8887eafdf1d0d807727d558fabd8b4df466c9021

**Comment by Sharlikran** [comment]
@Utumno is there a way yo rebase off of a certain commit.  For example I don't want to rebase off of the tip of dev or the tip of utumno-wip I want to rebese my changes off of the specific commit I indicate.

C1 - C2 - C3 - C4
        |                   \
        |                    Normal Rebase - C1 - C2
         \
           New Branch starting with C2 - then new changes C1 - C2 - C3

**Comment by Utumno** [comment]
`git rebase --onto` - check the docs I don't get your figure above - it's in the wiki too in the rebase article https://github.com/wrye-bash/wrye-bash/wiki/[github]-Branching-and-merging-to-dev-using-rebase

Always have gitk open and chekout temporary branches

---

Please before I start looking into the saves stuff use my commit for skyrim se support - not the 25000 lines one. Otherwise we will have huge conflicts - plus we must test _that_ commit is right - not the other ones.

**Comment by Sharlikran** [comment]
Basic support is added well enough to install files, ree the save game files, edit the header, and patch leveled lists.

**Comment by Utumno** [comment]
Sharl where is that support ? Was the save game masters isuue settled /

**Comment by Sharlikran** [comment]
330- skyrimse- support has the support for SSE. Yes the saves game issue is settled because there is no arguing the points I made nor Jon's confirmation of the header size.

**Comment by Utumno** [comment]
Great I see you rebased on current dev - but please replace the 40k lines commit https://github.com/Sharlikran/wrye-bash/commit/fa6af2620bd122d8e57d85f1c1c629e0c02add81 with the one I have that does not duplicate code. I am for my part going to merge some more of my wip branch to dev then turn the eye on this

**Comment by Sharlikran** [comment]
I think I'll keep the file as is for now until I figure out how to change the imports to grab records from the Skyrim records file then add classes to reflect the records that changed according to what Zilav and I have found for xEdit.  I'd like to know how to do that if you have time, maybe you could provide the first line like ``import ..records.skyrim MreHeader, MerActi,``` and so on.  Then if ``__init__.py`` has to have a different import briefly specify that.  If you are busy with other stuff that's fine, I don't want to keep you from what you are doing, and I think I can do it but it's easier for me to follow an example.

What would help, in regards to all my commits, is to ask me about my changes and offer a few ways to do things differently.  If I like the suggestions I can pick one.  Then the code does what I want and it's more in line with what you want as well.

As it stands, like I mentioned in the other issue I closed, regardless of whether or not I change anything else or try to enable another patcher I may not ever rebase again.  We are simply heading in two different directions.  Myself, and Wrye enthusiasts and supporters want all the features added that Wrye needs to provide what it does for Oblivion.  Currently it doesn't do that for Skyrim, Fallout 4 and now Skyrim SE.  You are still working on code stability, which is fine keep doing that.

I'm just making changes for personal use.

**Comment by Arthmoor** [comment]
I don't believe the points were settled because I still have perfectly
valid SSE generated saves that Bash falsely claims to be corrupt. They
can't be corrupt. They work in the game. I don't know how much more plainly
that needs to be stated.

**Comment by Utumno** [comment]
@Arthmoor please reply at https://github.com/wrye-bash/wrye-bash/issues/330

**Comment by Sharlikran** [comment]
I was working today on how to make sure renaming the plugin names worked correctly as I was having issues.  I'm going to disable the save tab at this time and I won't be working on it any more.  If Bethesda responds on the forums or a future update seems to resolve this, I'll revisit this.

To display the header Lojack and all other previous contributors assigned variables to determine how many bytes to read.  In the save games that have inconsistencies and report the error, those variables are filled with a number that is too large which causes an exception.

In fact I'm going to stop working on Wrye completley at this point.  Nothing against you Arthmoor, I don't mean any disrespect, but I keep wanting to update things for personal use and I can just see that it's a waste of time and effort.  Wrye Bash need to have support for more then just Oblivion and that obviously not the current goal.

**Comment by Utumno** [comment]
Who said it's not the current goal ?

**Comment by Sharlikran** [comment]
No disrespect Utumno, but I'm done talking about things.  I'll leave you to what you are doing I don't want to interfere and take up what little time you have to work on things.  I want to be considerate and I appreciate what you are doing, and I'll leave it at that.
