### ISSUE TITLE
Help with Fallout 3/Fallout NV added patchers

### ISSUE THREAD

**Issue by Sharlikran** [Sharlikran/wrye-bash#23]
I have cherry picked all the commits from [feature-sharlikran-valda-fallout](https://github.com/Sharlikran/wrye-bash/tree/feature-sharlikran-valda-fallout) to [dev-fallout-patcher-update](https://github.com/Sharlikran/wrye-bash/tree/dev-fallout-patcher-update) for Fallout 3 and Fallout NV.  It is rebased it off of my other branches which includes utumno-wip and dev-skyrim-patcher-loot-update.

I was unable to follow some of the changes.  I believe I only need help with three commits.

- [ ] Added class FidListsMerger : Old commit 4398d7f84266beae1c2b2e07b651d0ff1bbce97b : New Commit cd7b67bcf92c01f69d88cc95bcadf178e4d7f32a
 - The addition to mod_links.py, where do I put that now?
 - In gui_patchers.py is listLabel still required for class FidListsMerger?
- [ ] Added class DestructiblePatcher  : Old commit 016316bc529a95797bf6446ce50fe15589c772c3 : New Commit 946d917a49f722797dfa13fd81b4b3db2db80fbd
 - Is this one already correct?
- [ ] Added class WeaponModsPatcher : Old commit dedc652bbd52289394697d5dd619bfbbba6ba566 : New Commit 52753cd7b1821c91547c149d1aafa61e91f70a31
 - Is this one already correct?

**Comment by Sharlikran** [comment]
@Utumno when you have time can you look at this and see if ti's correct or if I overlooked something?

**Comment by Utumno** [comment]
Please now rebase wrye-bash:feature-sharlikran-valda-fallout and compare this to your rebase

Will have a look when I finish merging some of my branch to dev (week end ?)

**Comment by Sharlikran** [comment]
If you can't get to it for a week or so that's fine.  I don't want to impose.  However, all I'm looking for is how to mimic the three commits in the new code.

For me to go and refactor wrye-bash:feature-sharlikran-valda-fallout would take me several days and I'd be blindly rebasing it on my existing code.  I'd just be cutting and pasting stuff like in this commit 66d6ffab2d45890e842e6876da43345c696b8518 which I did because I wanted one of the patchers I added to work.

If I try to do what you ask it will lead to you telling me I did it wrong.  You are asking because you want me to rebase off of dev.  While I want a working version of Wrye that I can use while I play FO4 or SSE or Skyrim.  My code is rebased off of utumno-wip, loot v9.2 with the v0.10 masterlist, and all my SSE and FO4 stuff.

I was just looking to resolve those three commits and then I was going to see if it worked and whether or not I needed 66d6ffab2d45890e842e6876da43345c696b8518  at all.

**Comment by Utumno** [comment]
Ok sharl here you are: https://github.com/wrye-bash/wrye-bash/tree/feature-sharlikran-valda-fallout

This is the final version - contains all the fixes from my old rebase plus I solved the new conflict with FidListMerger - mod_links code should not be needed at all - just verify it prints the log correctly on "List patch Config" menu item

My _plog2 commit is on dev

In general:

I will be rebasing this branch on dev as soon as I can. So we are up to date with dev code. You can however rebase it yourself to double check - I don't foresee any conflicts now - except when I will move some of it to dev (for instance the factoring out of tesxedit code to game)

Fell free (in fact I encourage you) to rebase this branch on utumno-wip - let me know of any issues here (or in the forums). I will not be rebasing however over utumno-wip myself as it changes too often locally and my local tree is very complex at the moment. 

-----

The last merge was immensely complex - I was ill, stayed home for 2 days so I had time to merge but now I am more ill :P

While I recover and (merge some of more stable utumno-wip to dev) I would want you to (at your pace but please notify me only if really really needed):

- pull my latest utumno-wip -discard old is buggy (as always utumno-wip, it's bleeding edge - this one however is more stable)
- rebase your version over utumno-wip - use `--onto` to just rebase the commits on your branch
- I hope you have enabled rerere as I told you once - if not do it now - it will savce you from solving the same conflicts again and again - see the wiki for command
- rebase _my_ version on utumnno-wip

Compare the versions to make sure it's all right. In fact I am sure it's all right and the version we will keep is mine (except if you added commits which please add to my version too). My version contains fixes from code style to whatnot.

So I hope to just get an OK notification

------

In general when the dust settles we end up with  wrye-bash:feature-sharlikran-valda-fallout _on dev_. This will be based on my version and we will keep rebasing on dev and testing this (as I said, of course you are invited to keep a rebased version over my wip - I just can't do that, I just need the reference version on dev).

In general dev is the stable branch and whatever merge will take place from there. I intend to revisit fallout merging in 308 - but we need to have this one and only branch on dev set up first.

For now it is certainly not a priority however so keep mentions to minimum - the beta, bsa/b2a, loot and skyrim se (probably) are more than enough

Thanks!

**Comment by Utumno** [comment]
Also if you need to help you could:

- give me feedback on https://github.com/wrye-bash/wrye-bash/issues/148 I need to close that, I have requested feedback since forever!
- hash up a contributing.md - see https://github.com/wrye-bash/wrye-bash/issues/317 and loot's one: https://github.com/loot/loot/blob/dev/CONTRIBUTING.md - although we certainly need the reporting a bug section in ! No need for perfection - but as you have spent a lot of time helping users you are the ideal person for that - our contributing.md should be more geared towards users than developers.

Those will keep you busy I ~~hope~~ think :D

:+1:

**Comment by Sharlikran** [comment]
> Ok sharl here you are ... This is the final version - contains all the fixes from my old rebase plus I solved the new conflict with FidListMerger - mod_links code should not be needed at all - just verify it prints the log correctly on "List patch Config" menu item

I glanced at it and I think I can follow it.  I also think it resolves my concerns about what is and is not needed.

I think after I really comb through it I might be able to rebase it off of your new utumno-wip.  Thanks for taking the time to do that.  Hope you feel better.

**Comment by Sharlikran** [comment]
Also don't be offended by this but something that came to mind recently with a new news article on the Nexus.  Basically it would be nice to see someone help you or help with the Wrye project and turn it into a better tool.  Since I have no idea whether or not anyone would be interested or not in working with Wrye what I suggested may never happen.

It's a very [long read](https://forums.nexusmods.com/index.php?/topic/4940905-big-changes-for-the-nexus-mod-manager-and-the-introduction-of-tannin42-our-new-head-of-nmm-development/?p=43254180) so don't look at it when you have limited time or you feel sick or under the weather and need to rest.

**Comment by Utumno** [comment]
Thanks Sharl :)

I just skimmed - will have a closer look - this: 

- Sort the mods (excluding missing mods) in the same order as indicated in the save game header. Remaining files append to end of the list.

was in my mind too - should be easy now that I own load order ;)

----

Will proceed into merging more of my wip branch - just make sure everything works on https://github.com/wrye-bash/wrye-bash/tree/feature-sharlikran-valda-fallout and replace your branches with this so we are on the same boat - take your time and let me know.

meanwhile the utumno-wip will slim down hopefully...

**Comment by Sharlikran** [comment]
Well I was thinking you have gone to the trouble of you know, rebasing feature-sharlikran-valda-fallout, and you were not feeling well, and all that.  I really appreciated it.  I was thinking since you were taking the time to do things, I should at least try to rebase.  You mentioned I needed to try to rebase feature-sharlikran-valda-fallout on dev.  So I tried and whatever _plog2 is has me baffled.  It's not somethiong I can see online at github.com, it's only in gitk and when I click it to open it in a web browser it goes to my fork instead of the wrye-bash repo like I would expect it to.

I'm not being impatient or trying to frustrate you or revisit previous arguments.  I know you are getting to everything and that I need to just trust you as far as the projects progression.  I have already decided to do that.  However, like I said I'm just a player, modder, I just don't have any more time to learn complex git stuff, nor any time to develop wrye, but I do want to tinker with things because I need working functionality for patchers like 4 years ago.

Sometimes you ask if I can test utumno-wip and for the most part I don't have time.  However, since you are working hard on things yeah sometimes I try it and it works pretty good.  I like it and it has something I need so I use it.

I had more I was going to say but after spending about a week fiddling with things I have realized that nothing has changed.  There is just no way I can make Wrye do what I want and I have to just wait like everyone else.  It's a big job for you I know, and you have been working so hard on things.  I just wish I could help more but I can't.

If I were going to do anything with the project then as mentioned I don't know how many years ago there would have to be 0% refactoring and moving of code until all needed functionality was implemented for Skyrim, Fallout 4, and the soon to be released Skyrim SE.  Since that's not where you are and probably won't be for many more months.  I'm just going to stop all rebasing, testing of utumno-wip, and what not.  I'll just get some basic patching for leveled lists for Fallout 4 and Skyrim SE and Arthmoor and I can use it.  I won't be able to release it to the public or anything so nobody but the two of us will ever see it but that's just how it has to be though.

Thanks again for all your time and answers recently.  Take care.

**Comment by Utumno** [comment]
Thanks Sharl. Just to clear this up:

> My _plog2 commit is on dev

So what branch were you trying to rebase ? :D I have rebased on recent dev: https://github.com/wrye-bash/wrye-bash/commits/feature-sharlikran-valda-fallout

There is no plog in there !?

**Comment by Sharlikran** [comment]
Closing as current Wrye Flash support works with Valda's versions.  Refactoring prevents adding new patchers for Fallout 3 or Fallout new vegas without full knowledge of the changes.
