### ISSUE TITLE
Skyrim Screen Shot Decoding

### ISSUE THREAD

**Issue by Sharlikran** [Sharlikran/wrye-bash#24]
Moving to my issue tracker so I can focus on accurately decoding the files.

```
struct IMAGE {
    uint width;
    uint height;
    ushort something;
    struct COLOR {
        ubyte R;
        ubyte G;
        ubyte B;
        ubyte A;
    } color[width*height];
} image;
```
Okay @jonwd7, so if I understand that, uint is 32 bit unsigned, ushort is 16 bit unsigned, and ubyte is 8 bit unsigned, correct?  Thanks for everything so far.

That might be why the things are not showing up.  I am not looking for the screen shot data one ushot after the width and height.  Also I was about to investigate why the original Skyrim save files and the screen shot are exactly two bytes different from the new format.  So that ushort is interesting.

Do you have that extra ushort in an old skyrim save?  I am going to make all new save games for each version right now.  With exactly the same mods installed.

**Comment by jonwd7** [comment]
From the other issue:

    struct IMAGE {
        uint width;
        uint height;
        if ( header.version > 9 )
            ushort something;
        struct COLOR {
            ubyte R;
            ubyte G;
            ubyte B;
            if ( header.version > 9 )
                ubyte A;
        } color[width*height] <optimize=true>;
    } image;

Works on both old and new saves.

**Comment by Sharlikran** [comment]
Thanks.  I have this done and I verified Fallout 4 also.  I really appreciate you mentioning those 2 bytes.  I know I have said that like ten times but that really was what was holding things up.  Thanks again.
